//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineArtGallery.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Artdetail
    {
        public int id { get; set; }
        public string nameart { get; set; }
        public string hidemail { get; set; }
        public string nameartist { get; set; }
        public string descriptionofart { get; set; }
        public string artsize { get; set; }
        public int price { get; set; }
        public string avali { get; set; }
        public string review { get; set; }
        public string img { get; set; }
        public string appstatus { get; set; }
        public HttpPostedFileBase File { get; set; }


    }
}
