//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineArtGallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inibuyer
    {
        public int id { get; set; }
        public string users { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string email { get; set; }
        public string contacto { get; set; }
        public string contactt { get; set; }
        public string adress { get; set; }
        public string region { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string pcode { get; set; }
        public string gender { get; set; }
        public string pass { get; set; }
    }
}
