//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineArtGallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reqacce
    {
        public int reqid { get; set; }
        public string requsers { get; set; }
        public string reqfname { get; set; }
        public string reqlname { get; set; }
        public string reqemail { get; set; }
        public string reqcontacto { get; set; }
        public string reqcontactt { get; set; }
        public string reqadress { get; set; }
        public string reqregion { get; set; }
        public string reqcity { get; set; }
        public string reqcountry { get; set; }
        public string reqpcode { get; set; }
        public string reqgender { get; set; }
        public string reqpass { get; set; }
        public Nullable<int> reqstatus { get; set; }
    }
}
